image:
  - Visual Studio 2015
  - Ubuntu

environment:
  matrix:
    # node.js
    - nodejs_version: "6.15.0"
    - nodejs_version: "7.10.1"
    - nodejs_version: "8.14.0"
    - nodejs_version: "9.11.2"
    - nodejs_version: "10.14.0"
    - nodejs_version: "11.3.0"

install:
  - cmd: powershell wget -UseBasicParsing https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.zip -OutFile nvm-setup.zip
  - cmd: powershell Expand-Archive -Path nvm-setup.zip -DestinationPath .
  - cmd: powershell $app = Get-WmiObject -Class Win32_Product | Where-Object {$_.Name -match "Node.js"}
  - cmd: powershell echo "app : $app"
  - cmd: powershell Start-Process -Wait -FilePath 'nvm-setup.exe' -ArgumentList '/SILENT /SUPPRESSMSGBOXES /q /s' -PassThru
  - cmd: powershell Start-Process -Wait -FilePath '%AppData%\nvm\nvm.exe' -ArgumentList 'install $env:nodejs_version 64'
  - cmd: powershell Start-Process -Wait -FilePath '%AppData%\nvm\nvm.exe' -ArgumentList 'use $env:nodejs_version 64'
  - node -p "[process.version,process.arch].join(' ')"
  - npm --version
  - dotnet --version  #- cmd: powershell Install-Product node $env:nodejs_version x64
  - sh: sudo apt-get -qq update
  - sh: sudo apt-get -y -qq install build-essential libgconf-2-4 python libglib2.0-dev
  - sh: nvm install $nodejs_version
  - npm install -q
  - sh: npm i xunit-viewer --silent &> /dev/null
  - cmd: npm i xunit-viewer >nul

test_script:

  - npm test
  - node tools/coverage.js
  - cmd: SET EDGE_USE_CORECLR=1 & npm test
  - cmd: SET EDGE_USE_CORECLR=1 & node tools/coverage.js
  - sh: EDGE_USE_CORECLR=1 npm test
  - sh: EDGE_USE_CORECLR=1 node tools/coverage.js

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = '.\test-results.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path '.\test-results.xml'))
      Push-AppveyorArtifact (Resolve-Path '.\test-results.xml')
      Push-AppveyorArtifact (Resolve-Path '.\test-results-xunit-viewer.xml')
      Push-AppveyorArtifact (Resolve-Path '.\test-results-xunit-viewer.html')

build: off