image:
#- Ubuntu
- Visual Studio 2015

environment:
  matrix:
    # node.js
    - nodejs_version: "6.15.0"
    - nodejs_version: "7.10.1"
    - nodejs_version: "8.14.0"
    - nodejs_version: "9.11.2"
    - nodejs_version: "10.14.0"
    - nodejs_version: "11.3.0"

install:
  - cmd: powershell Install-Product node $env:nodejs_version
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y apt-transport-https build-essential libgconf-2-4 python libglib2.0-dev
  - sh: nvm install $nodejs_version
  - npm install
  - npm i xunit-viewer

test_script:
  - node --version
  - npm --version
  - dotnet --version
  - npm test
  - node tools/coverage.js
  - cmd: SET EDGE_USE_CORECLR=1 & npm test
  - cmd: SET EDGE_USE_CORECLR=1 & node tools/coverage.js
  - sh: EDGE_USE_CORECLR=1 npm test
  - sh: EDGE_USE_CORECLR=1 node tools/coverage.js

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = '.\test-results.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path '.\test-results.xml'))
      Push-AppveyorArtifact (Resolve-Path '.\test-results.xml')
      Push-AppveyorArtifact (Resolve-Path '.\test-results-xunit-viewer.xml')
      Push-AppveyorArtifact (Resolve-Path '.\test-results-xunit-viewer.html')

build: off