image:
  - Visual Studio 2015
  - Ubuntu2204
  - macos-monterey

environment:
  matrix:
    # node.js
    - nodejs: "16"
    - nodejs: "18"
    - nodejs: "20"

install:
  - sh: if [ "$APPVEYOR_BUILD_WORKER_IMAGE" = 'Ubuntu2204' ]; then sudo apt-get -qq update && sudo apt-get -y -qq install build-essential libgconf-2-4 python3 libglib2.0-dev; fi
  - ps: Write-Host "Downloading .NET Core 7 SDK..."
  - ps: (New-Object System.Net.WebClient).DownloadFile('https://download.visualstudio.microsoft.com/download/pr/f2ec926e-0d98-4a8b-8c70-722ccc2ca0e5/b59941b0c60f16421679baafdb7e9338/dotnet-sdk-7.0.407-win-x64.exe','dotnet-core-sdk.exe')
  - ps: Write-Host "Installing .NET Core SDK..."
  - ps: Invoke-Command -ScriptBlock { dotnet-core-sdk.exe /S /v/qn }
  - cmd: powershell Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs) x64
  - sh: nvm ls
  - sh: nvm install $nodejs
  - sh: nvm use $nodejs
  - node -p "[process.version,process.arch].join(' ')"
  - dotnet --version
  - npm install -q
  - cmd: npm i -q  xunit-viewer >nul
  - sh: npm i xunit-viewer --silent &> /dev/null

test_script:

  - cmd: npm test
  - cmd: node tools/coverage.js
  - cmd: SET EDGE_USE_CORECLR=1 & npm test
  - cmd: SET EDGE_USE_CORECLR=1 & node tools/coverage.js
  - sh: EDGE_USE_CORECLR=1 npm test
  - sh: EDGE_USE_CORECLR=1 node tools/coverage.js

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = '.\test-results.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path '.\test-results.xml'))
      Push-AppveyorArtifact (Resolve-Path '.\test-results.xml')
      Push-AppveyorArtifact (Resolve-Path '.\test-results-xunit-viewer.xml')
      Push-AppveyorArtifact (Resolve-Path '.\test-results-xunit-viewer.html')

skip_commits:
  files:
    - samples/*
    - stress/*
    - performance/*
    - '**/*.md'
    - '**/*.d.ts'
    - '**/*.bat'
    - '.travis.yml'
    - 'Dockerfile'
    - 'README'

build: off