version: 2.1
orbs:
  node: circleci/node@5
  win: circleci/windows@5.0
  macos: circleci/macos@5.0

executors:
  node: 
    docker:
      - image: node/default
  windows: 
    machine:
      image: windows-server-2022-gui:current
    resource_class: windows.medium
  macos: 
    macos:
      xcode: 15.2.0
    resource_class: macos.m1.medium.gen1

refs:
  steps:
    - &InstallNode
      node/install:
        node-version: << parameters.node-version >>
    - &InstallDotnet
      run:
        shell: bash
        name: Install dotnet
        command: |
          if [[ $OSTYPE == darwin* ]]; then
              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
              brew install --cask dotnet-sdk
          elif [[ $OSTYPE == linux* ]]; then
            wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update
            sudo apt-get install -y dotnet-sdk-8.0
            sudo rm packages-microsoft-prod.deb
          fi
    - &Versions
      run:
        name: Versions
        command: node -v && npm -v && dotnet --version
    - &NpmInstall
      run:
        name: NPM Install
        command: npm install
    - &Test
      run:
        shell: bash
        name: Test
        command: |
          if [[ $OSTYPE == darwin* || $OSTYPE == linux* ]]; then
              EDGE_USE_CORECLR=1 node tools/test.js circleci
          else
            node tools/test.js circleci
            node tools/test.js circleci coreclr
          fi

jobs:
  test-node:
    # Install node dependencies and run tests
    executor: win/default
    
    steps:
      - checkout
      - *InstallDotnet
      # - node/install-packages:
      #     cache-path: ~/project/node_modules
      #     override-ci-command: npm install
      - *Versions
      - run: npm install 
      - *Test
      # - run:
      #     name: Run tests
      #     command: EDGE_USE_CORECLR=1 node tools/test.js circleci --passWithNoTests
      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./mochawesome.json
          destination: mochawesome.json

workflows:
  build-and-test:
    jobs:
      - test-node:
          matrix:
            parameters:
              os: ['node', 'windows', 'macos']


