version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test-node:
    # Install node dependencies and run tests
    executor: node/default
    steps:
      - checkout

      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install

      - run:
          name: Run tests
          command: EDGE_USE_CORECLR=1 node tools/test.js circleci --passWithNoTests

      - store_artifacts:
          path: ./mochawesome.json
          destination: mochawesome.json

workflows:
  build-and-test:
    jobs:
      - test-node
    # - deploy:
    #     requires:
    #       - test-node
