name: 'Test built Windows binary'
description: 'Test built Windows binary'
inputs:
  os:
    description: 'runs-on'
    required: false
    default: 'windows-2022'
  node:
    description: 'Node version'
    required: true

runs:
  using: "composite"
  steps:

    - name: Create release folder
      if:  runner.os == 'Windows'
      shell: pwsh
      run: |
        cmd /c if not exist "lib\native\win32\ia32\${{ inputs.node }}" mkdir "lib\native\win32\ia32\${{ inputs.node }}"
        cmd /c if not exist "lib\native\win32\x64\${{ inputs.node }}" mkdir "lib\native\win32\x64\${{ inputs.node }}"
        cmd /c if not exist "lib\native\win32\arm64\${{ inputs.node }}" mkdir "lib\native\win32\arm64\${{ inputs.node }}"

    - name: Create release folder
      if:  runner.os == 'macOS'
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          try {
            const fs = require('fs')
              fs.mkdirSync('lib/native/darwin/x64/${{ inputs.node }}', { recursive: true });
              fs.mkdirSync('lib/native/darwin/arm64/${{ inputs.node }}', { recursive: true });
          } catch(err) {
            core.error("Error creating release directory")
            core.setFailed(err)
          }

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: release
        pattern: edge-js-${{ inputs.node }}*

    - name: List artifacts
      shell: bash
      run: ls -R release

    - name: Copy artifacts
      if:  runner.os == 'Windows'
      shell: pwsh
      run: |
        cmd /c copy /y release\edge-js-${{ inputs.node }}\x64\${{ inputs.node }}\edge_*.node lib\native\win32\x64\${{ inputs.node }}

    - name: Copy artifacts
      if:  runner.os == 'macOS'
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          try {
            const fs = require('fs')
              fs.copyFileSync('release/edge-js-${{ inputs.node }}/x64/${{ inputs.node }}/edge_coreclr.node', 'lib/native/darwin/x64/${{ inputs.node }}/edge_coreclr.node');
              fs.copyFileSync('release/edge-js-${{ inputs.node }}/x64/${{ inputs.node }}/edge_coreclr.node', 'lib/native/darwin/arm64/${{ inputs.node }}/edge_coreclr.node');
          } catch(err) {
            core.error("Error creating release directory")
            core.setFailed(err)
          }
          
    - name: Setup env
      uses: ./.github/actions/setup-env
      with:
        node: ${{ inputs.node }}
        os: ${{ inputs.os }}

    - name: Test
      uses: ./.github/actions/test-windows
      with:
        node: ${{ inputs.node }}
  
    - name: Test report
      uses: ./.github/actions/create-test-report
      with:
        node: ${{ inputs.node }}
        os: ${{ inputs.os }}
        name: 'build-tests'
 