name: Main

on: push

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # SDK Version to use; x will use the latest version of the 8.0 channel
      - name: Install dependencies
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
            EDGE_USE_CORECLR=1 npm i
          elif [ "$RUNNER_OS" == "Windows" ]; then
            npm i
          elif [ "$RUNNER_OS" == "macOS" ]; then
            EDGE_USE_CORECLR=1 npm i
          fi
      - name: Run tests
        run:   |
          if [ "$RUNNER_OS" == "Linux" ]; then
            EDGE_USE_CORECLR=1 npm test
          elif [ "$RUNNER_OS" == "Windows" ]; then
            npm test
            SET EDGE_USE_CORECLR=1 & npm test
          elif [ "$RUNNER_OS" == "macOS" ]; then
            EDGE_USE_CORECLR=1 npm test
          fi
